# Copyright 2024 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name = "storage-manager"
main = "src/index.ts"
logpush = true
compatibility_date = "2023-10-30"
workers_dev = false

# 必须启用，因为 Signal 使用了 Node.js crypto 的流式 HMAC
compatibility_flags = ["nodejs_compat"]

# 1. 绑定你的自定义域名 (替代默认的 workers.dev 域名)
routes = [
  { pattern = "storage-manager.antennapro.org/*", custom_domain = true }
]

# 2. 核心环境变量 (Signal 官方强烈要求的 GCS 存储桶)
#[vars]
#GCS_BUCKET = "填入你的GCS存储桶名称"

# 3. 绑定的 R2 存储桶
r2_buckets = [
	{ binding = "ATTACHMENT_BUCKET", bucket_name = "antenna-v2-attachments", preview_bucket_name = "antenna-v2-attachments" },
	{ binding = "BACKUP_BUCKET", bucket_name = "antenna-v2-backups", preview_bucket_name = "antenna-v2-backups" }
]
